// Autogenerated from Pigeon (v22.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private class NamesExamplePigeonCodecReader: FlutterStandardReader {
}

private class NamesExamplePigeonCodecWriter: FlutterStandardWriter {
}

private class NamesExamplePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return NamesExamplePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return NamesExamplePigeonCodecWriter(data: data)
  }
}

class NamesExamplePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = NamesExamplePigeonCodec(readerWriter: NamesExamplePigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NamesStorage {
  func getNames() throws -> [String]
  func getName(id: String) throws -> String?
  func saveName(id: String, name: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NamesStorageSetup {
  static var codec: FlutterStandardMessageCodec { NamesExamplePigeonCodec.shared }
  /// Sets up an instance of `NamesStorage` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NamesStorage?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getNamesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_channels.NamesStorage.getNames\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getNamesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getNames()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getNamesChannel.setMessageHandler(nil)
    }
    let getNameChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_channels.NamesStorage.getName\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getNameChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        do {
          let result = try api.getName(id: idArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getNameChannel.setMessageHandler(nil)
    }
    let saveNameChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_channels.NamesStorage.saveName\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveNameChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        let nameArg = args[1] as! String
        do {
          try api.saveName(id: idArg, name: nameArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      saveNameChannel.setMessageHandler(nil)
    }
  }
}
